name: wf_fe_build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Image FE
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      IMAGE_TAG: $(git rev-parse --short HEAD)
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_URL }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Overwrite .env file variables
        run: |
          echo "${{ vars['ENVVAR_WEBSITE'] }}" > ./website/.env

          cat ./website/.env

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/crawler-website:${{ env.IMAGE_TAG }} ./website
          docker tag ${{ vars.DOCKER_USERNAME }}/crawler-website:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/crawler-website:latest
      
      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-website:latest
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-website:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy_${{ inputs.APP_NAME }}
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      IMAGE_TAG: $(git rev-parse --short HEAD)
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Checkout infra repository
        uses: actions/checkout@v4
        with:
          repository: duytran2782/devguild-infra
          ref: main
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Update image tag helm chart
        working-directory: helm
        run: |
          oldValue="tag:.*"
          newValue="tag: ${{ env.IMAGE_TAG }}"

          cd app/website/

          ls -al
          echo $(pwd)
          sed -i "s/$oldValue/$newValue/" ./values.yaml
          
          git config user.email "CI@gmail.com"
          git config user.name "CI"
          
          git add .
          git commit -m "Update image to Website with tag ${{ env.IMAGE_TAG }}" || true
          git push origin main || true
