name: wf_dagger_build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Image FE
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full Git history for commit ID

      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)"

      - name: Overwrite .env file variables
        run: |
          echo "${{ vars['ENVVAR_WEBSITE'] }}" > ./website/.env

          cat ./website/.env

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Run dagger pipeline
        run: |
          go run .dagger/main.go
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_URL: ${{ vars.DOCKER_URL }}
          IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}
