name: wf_dagger_test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Debug Unit Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: read
      pull-requests: write
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dagger/dagger-for-github@8.0.0

      - name: Run dagger Debug
        run: |
          dagger call check --github-token GITHUB_TOKEN --commit ${{ github.sha }} --model gemini-2.0-flash
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
